import type { Event_AddToList } from 'generated/proto/event_add_to_list_pb';
import type { Event_ConnectionClosed } from 'generated/proto/event_connection_closed_pb';
import type { Event_GameJoined } from 'generated/proto/event_game_joined_pb';
import type { Event_ListRooms } from 'generated/proto/event_list_rooms_pb';
import type { Event_NotifyUser } from 'generated/proto/event_notify_user_pb';
import type { Event_RemoveFromList } from 'generated/proto/event_remove_from_list_pb';
import type { Event_ReplayAdded } from 'generated/proto/event_replay_added_pb';
import type { Event_ServerCompleteList } from 'generated/proto/event_server_complete_list_pb';
import type { Event_ServerIdentification } from 'generated/proto/event_server_identification_pb';
import type { Event_ServerMessage } from 'generated/proto/event_server_message_pb';
import type { Event_ServerShutdown } from 'generated/proto/event_server_shutdown_pb';
import type { Event_UserJoined } from 'generated/proto/event_user_joined_pb';
import type { Event_UserLeft } from 'generated/proto/event_user_left_pb';
import type { Event_UserMessage } from 'generated/proto/event_user_message_pb';
import type { Event_PlayerPropertiesChanged } from 'generated/proto/event_player_properties_changed_pb';

export type AddToListData = Event_AddToList;
export type ConnectionClosedData = Event_ConnectionClosed;
export type GameJoinedData = Event_GameJoined;
export type ListRoomsData = Event_ListRooms;
export type NotifyUserData = Event_NotifyUser;
export type RemoveFromListData = Event_RemoveFromList;
export type ReplayAddedData = Event_ReplayAdded;
export type ServerCompleteListData = Event_ServerCompleteList;
export type ServerIdentificationData = Event_ServerIdentification;
export type ServerMessageData = Event_ServerMessage;
export type ServerShutdownData = Event_ServerShutdown;
export type UserJoinedData = Event_UserJoined;
export type UserLeftData = Event_UserLeft;
export type UserMessageData = Event_UserMessage;
export type PlayerGamePropertiesData = Event_PlayerPropertiesChanged;
