syntax = "proto2";

message ServerInfo_ReportComment {
    optional string author_name = 1;
    optional string comment_text = 2;
    optional int64 comment_time = 3;
    optional bool is_moderator = 4;
}

message ServerInfo_Report {
    optional int32 report_id = 1;

    optional string reporter_name = 2;
    optional string reported_user_name = 3;

    optional int32 game_id = 4;
    optional int32 replay_id = 5;
    optional int32 room_id = 6;

    optional string category = 7;
    optional string status = 8;

    optional string description = 9;

    optional int64 report_time = 10;

    optional string assigned_mod_name = 11;

    optional int64 resolution_time = 12;

    repeated ServerInfo_ReportComment comments = 13;

    optional string chat_log = 14;

    optional string resolution_note = 15;
}
