import type { QTableProps } from 'quasar';

interface Games {
  age: string;
  description: string;
  creator: string;
  type: string;
  restrictions: string;
  players: string;
  spectators: string | number;
}

const restrictions = ['🔒 password', 'reg. users only', 'buddies only'];

export const gameColumns: QTableProps['columns'] = [
  { name: 'Age', label: 'Age', field: 'age', sortable: true },
  {
    name: 'Description',
    required: true,
    label: 'Description',
    align: 'left',
    field: 'description',
    sortable: true,
  },
  {
    name: 'Creator',
    required: true,
    label: 'Creator',
    align: 'left',
    field: 'creator',
    sortable: true,
  },
  { name: 'Type', required: true, label: 'Type', align: 'left', field: 'type', sortable: true },
  {
    name: 'Restrictions',
    required: true,
    label: 'Restrictions',
    align: 'left',
    field: 'restrictions',
    sortable: true,
  },
  {
    name: 'Players',
    required: true,
    label: 'Players',
    align: 'left',
    field: 'players',
    sortable: true,
  },
  {
    name: 'Spectators',
    required: true,
    label: 'Spectators',
    align: 'left',
    field: 'spectators',
    sortable: true,
  },
];
export const games: Games[] = [
  {
    age: '0 hr',
    description: 'cEDH 4 man hibachi tacos',
    creator: 'Dustin',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '3 hr',
    description: 'Modern madness with spicy ramen',
    creator: 'Ava',
    type: 'Modern',
    restrictions: restrictions[1] || '',
    players: `${2}/${4}`,
    spectators: 1,
  },
  {
    age: '4 hr',
    description: 'Legacy league pizza night',
    creator: 'Kai',
    type: 'Legacy',
    restrictions: restrictions[2] || '',
    players: `${3}/${4}`,
    spectators: 2,
  },
  {
    age: '4 hr',
    description: 'Commander chaos draft BBQ',
    creator: 'Riley',
    type: 'Commander',
    restrictions: restrictions[0] || '',
    players: `${4}/${4}`,
    spectators: 5,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
  {
    age: '5+ hr',
    description: 'Budget cEDH burrito brawl',
    creator: 'Jordan',
    type: 'Vintage',
    restrictions: restrictions[0] || '',
    players: `${1}/${4}`,
    spectators: 0,
  },
];
