export const Types = {
  CLEAR_STORE: "[Server] Clear Store",
  CONNECT_SERVER: "[Server] Connect Server",
  CONNECTION_CLOSED: "[Server] Connection Closed",
  SERVER_MESSAGE: "[Server] Server Message",
  UPDATE_BUDDY_LIST: "[Server] Update Buddy List",
  ADD_TO_BUDDY_LIST: "[Server] Add to Buddy List",
  REMOVE_FROM_BUDDY_LIST: "[Server] Remove from Buddy List",
  UPDATE_IGNORE_LIST: "[Server] Update Ignore List",
  ADD_TO_IGNORE_LIST: "[Server] Add to Ignore List",
  REMOVE_FROM_IGNORE_LIST: "[Server] Remove from Ignore List",
  UPDATE_INFO: "[Server] Update Info",
  UPDATE_STATUS: "[Server] Update Status",
  UPDATE_USER: "[Server] Update User",
  UPDATE_USERS: "[Server] Update Users",
  USER_JOINED: "[Server] User Joined",
  USER_LEFT: "[Server] User Left",
  VIEW_LOGS: "[Server] View Logs",
  CLEAR_LOGS: "[Server] Clear Logs"
};
