import { Actions } from './server.actions';

const a = Actions;

export const Types = {
  INITIALIZED: a.initialized.type,
  CLEAR_STORE: a.clearStore.type,
  CONNECTION_ATTEMPTED: a.connectionAttempted.type,
  LOGIN_SUCCESSFUL: a.loginSuccessful.type,
  LOGIN_FAILED: a.loginFailed.type,
  CONNECTION_FAILED: a.connectionFailed.type,
  TEST_CONNECTION_SUCCESSFUL: a.testConnectionSuccessful.type,
  TEST_CONNECTION_FAILED: a.testConnectionFailed.type,
  SERVER_MESSAGE: a.serverMessage.type,
  UPDATE_BUDDY_LIST: a.updateBuddyList.type,
  ADD_TO_BUDDY_LIST: a.addToBuddyList.type,
  REMOVE_FROM_BUDDY_LIST: a.removeFromBuddyList.type,
  UPDATE_IGNORE_LIST: a.updateIgnoreList.type,
  ADD_TO_IGNORE_LIST: a.addToIgnoreList.type,
  REMOVE_FROM_IGNORE_LIST: a.removeFromIgnoreList.type,
  UPDATE_INFO: a.updateInfo.type,
  UPDATE_STATUS: a.updateStatus.type,
  UPDATE_USER: a.updateUser.type,
  UPDATE_USERS: a.updateUsers.type,
  USER_JOINED: a.userJoined.type,
  USER_LEFT: a.userLeft.type,
  VIEW_LOGS: a.viewLogs.type,
  CLEAR_LOGS: a.clearLogs.type,
  REGISTRATION_REQUIRES_EMAIL: a.registrationRequiresEmail.type,
  REGISTRATION_SUCCESS: a.registrationSuccess.type,
  REGISTRATION_FAILED: a.registrationFailed.type,
  REGISTRATION_EMAIL_ERROR: a.registrationEmailError.type,
  REGISTRATION_PASSWORD_ERROR: a.registrationPasswordError.type,
  REGISTRATION_USERNAME_ERROR: a.registrationUserNameError.type,
  CLEAR_REGISTRATION_ERRORS: a.clearRegistrationErrors.type,
  ACCOUNT_AWAITING_ACTIVATION: a.accountAwaitingActivation.type,
  ACCOUNT_ACTIVATION_SUCCESS: a.accountActivationSuccess.type,
  ACCOUNT_ACTIVATION_FAILED: a.accountActivationFailed.type,
  RESET_PASSWORD_REQUESTED: a.resetPassword.type,
  RESET_PASSWORD_FAILED: a.resetPasswordFailed.type,
  RESET_PASSWORD_CHALLENGE: a.resetPasswordChallenge.type,
  RESET_PASSWORD_SUCCESS: a.resetPasswordSuccess.type,
  ADJUST_MOD: a.adjustMod.type,
  RELOAD_CONFIG: a.reloadConfig.type,
  SHUTDOWN_SERVER: a.shutdownServer.type,
  UPDATE_SERVER_MESSAGE: a.updateServerMessage.type,
  ACCOUNT_PASSWORD_CHANGE: a.accountPasswordChange.type,
  ACCOUNT_EDIT_CHANGED: a.accountEditChanged.type,
  ACCOUNT_IMAGE_CHANGED: a.accountImageChanged.type,
  GET_USER_INFO: a.getUserInfo.type,
  NOTIFY_USER: a.notifyUser.type,
  SERVER_SHUTDOWN: a.serverShutdown.type,
  USER_MESSAGE: a.userMessage.type,
  ADD_TO_LIST: a.addToList.type,
  REMOVE_FROM_LIST: a.removeFromList.type,
  BAN_FROM_SERVER: a.banFromServer.type,
  BAN_HISTORY: a.banHistory.type,
  WARN_HISTORY: a.warnHistory.type,
  WARN_LIST_OPTIONS: a.warnListOptions.type,
  WARN_USER: a.warnUser.type,
  GRANT_REPLAY_ACCESS: a.grantReplayAccess.type,
  FORCE_ACTIVATE_USER: a.forceActivateUser.type,
  GET_ADMIN_NOTES: a.getAdminNotes.type,
  UPDATE_ADMIN_NOTES: a.updateAdminNotes.type,
  // Replay
  REPLAY_LIST: a.replayList.type,
  REPLAY_ADDED: a.replayAdded.type,
  REPLAY_MODIFY_MATCH: a.replayModifyMatch.type,
  REPLAY_DELETE_MATCH: a.replayDeleteMatch.type,
  // Deck Storage
  BACKEND_DECKS: a.backendDecks.type,
  DECK_NEW_DIR: a.deckNewDir.type,
  DECK_DEL_DIR: a.deckDelDir.type,
  DECK_UPLOAD: a.deckUpload.type,
  DECK_DELETE: a.deckDelete.type,
  DECK_DOWNLOADED: a.deckDownloaded.type,
  REPLAY_DOWNLOADED: a.replayDownloaded.type,
  // User games
  GAMES_OF_USER: a.gamesOfUser.type,
} as const;
