export const Types = {
  INITIALIZED: '[Server] Initialized',
  CLEAR_STORE: '[Server] Clear Store',
  LOGIN_SUCCESSFUL: '[Server] Login Successful',
  LOGIN_FAILED: '[Server] Login Failed',
  CONNECTION_CLOSED: '[Server] Connection Closed',
  CONNECTION_FAILED: '[Server] Connection Failed',
  TEST_CONNECTION_SUCCESSFUL: '[Server] Test Connection Successful',
  TEST_CONNECTION_FAILED: '[Server] Test Connection Failed',
  SERVER_MESSAGE: '[Server] Server Message',
  UPDATE_BUDDY_LIST: '[Server] Update Buddy List',
  ADD_TO_BUDDY_LIST: '[Server] Add to Buddy List',
  REMOVE_FROM_BUDDY_LIST: '[Server] Remove from Buddy List',
  UPDATE_IGNORE_LIST: '[Server] Update Ignore List',
  ADD_TO_IGNORE_LIST: '[Server] Add to Ignore List',
  REMOVE_FROM_IGNORE_LIST: '[Server] Remove from Ignore List',
  UPDATE_INFO: '[Server] Update Info',
  UPDATE_STATUS: '[Server] Update Status',
  UPDATE_USER: '[Server] Update User',
  UPDATE_USERS: '[Server] Update Users',
  USER_JOINED: '[Server] User Joined',
  USER_LEFT: '[Server] User Left',
  VIEW_LOGS: '[Server] View Logs',
  CLEAR_LOGS: '[Server] Clear Logs',
  REGISTRATION_REQUIRES_EMAIL: '[Server] Registration Requires Email',
  REGISTRATION_SUCCES: '[Server] Registration Success',
  REGISTRATION_FAILED: '[Server] Registration Failed',
  REGISTRATION_EMAIL_ERROR: '[Server] Registration Email Error',
  REGISTRATION_PASSWORD_ERROR: '[Server] Registration Password Error',
  REGISTRATION_USERNAME_ERROR: '[Server] Registration Username Error',
  ACCOUNT_AWAITING_ACTIVATION: '[Server] Account Awaiting Activation',
  ACCOUNT_ACTIVATION_SUCCESS: '[Server] Account Activation Success',
  ACCOUNT_ACTIVATION_FAILED: '[Server] Account Activation Failed',
  RESET_PASSWORD_REQUESTED: '[Server] Reset Password Requested',
  RESET_PASSWORD_FAILED: '[Server] Reset Password Failed',
  RESET_PASSWORD_CHALLENGE: '[Server] Reset Password Challenge',
  RESET_PASSWORD_SUCCESS: '[Server] Reset Password Success',
  ADJUST_MOD: '[Server] Adjust Mod',
  RELOAD_CONFIG: '[Server] Reload Config',
  SHUTDOWN_SERVER: '[Server] Shutdown Server',
  UPDATE_SERVER_MESSAGE: '[Server] Update Server Message',
  ACCOUNT_PASSWORD_CHANGE: '[Server] Account Password Change',
  ACCOUNT_EDIT_CHANGED: '[Server] Account Edit Changed',
  ACCOUNT_IMAGE_CHANGED: '[Server] Account Image Changed',
  DIRECT_MESSAGE_SENT: '[Server] Direct Message Sent',
  GET_USER_INFO: '[Server] Get User Info',
  NOTIFY_USER: '[Server] Notify User',
  SERVER_SHUTDOWN: '[Server] Server Shutdown',
  USER_MESSAGE: '[Server] User Message',
  ADD_TO_LIST: '[Server] Add To List',
  REMOVE_FROM_LIST: '[Server] Remove From List',
  BAN_FROM_SERVER: '[Server] Ban From Server',
  BAN_HISTORY: '[Server] Ban History',
  WARN_HISTORY: '[Server] Warn History',
  WARN_LIST_OPTIONS: '[Server] Warn List Options',
  WARN_USER: '[Server] Warn User',
};
