export const Types = {
  CLEAR_STORE: '[Server] Clear Store',
  LOGIN_SUCCESSFUL: '[Server] Login Successful',
  LOGIN_FAILED: '[Server] Login Failed',
  CONNECTION_CLOSED: '[Server] Connection Closed',
  SERVER_MESSAGE: '[Server] Server Message',
  UPDATE_BUDDY_LIST: '[Server] Update Buddy List',
  ADD_TO_BUDDY_LIST: '[Server] Add to Buddy List',
  REMOVE_FROM_BUDDY_LIST: '[Server] Remove from Buddy List',
  UPDATE_IGNORE_LIST: '[Server] Update Ignore List',
  ADD_TO_IGNORE_LIST: '[Server] Add to Ignore List',
  REMOVE_FROM_IGNORE_LIST: '[Server] Remove from Ignore List',
  UPDATE_INFO: '[Server] Update Info',
  UPDATE_STATUS: '[Server] Update Status',
  UPDATE_USER: '[Server] Update User',
  UPDATE_USERS: '[Server] Update Users',
  USER_JOINED: '[Server] User Joined',
  USER_LEFT: '[Server] User Left',
  VIEW_LOGS: '[Server] View Logs',
  CLEAR_LOGS: '[Server] Clear Logs',
  REGISTRATION_REQUIRES_EMAIL: '[Server] Registration Requires Email',
  REGISTRATION_FAILED: '[Server] Registration Failed',
  REGISTRATION_EMAIL_ERROR: '[Server] Registration Email Error',
  REGISTRATION_PASSWORD_ERROR: '[Server] Registration Password Error',
  REGISTRATION_USERNAME_ERROR: '[Server] Registration Username Error',
  ACCOUNT_AWAITING_ACTIVATION: '[Server] Account Awaiting Activation',
  ACCOUNT_ACTIVATION_SUCCESS: '[Server] Account Activation Success',
  ACCOUNT_ACTIVATION_FAILED: '[Server] Account Activation Failed',
  RESET_PASSWORD_REQUESTED: '[Server] Reset Password Requested',
  RESET_PASSWORD_FAILED: '[Server] Reset Password Failed',
  RESET_PASSWORD_CHALLENGE: '[Server] Reset Password Challenge',
  RESET_PASSWORD_SUCCESS: '[Server] Reset Password Success'
};
