from archlinux:latest

RUN pacman --sync --refresh --sysupgrade --needed \
    base-devel \
    cmake \
    git \
    protobuf \
    qt5-base \
    qt5-multimedia \
    qt5-svg \
    qt5-tools \
    qt5-websockets
