#!/bin/bash

# SCHEDULE WITH CRONTAB BASED ON TIME PERIOD REPLAYS SHOULD BE SAVED UNTIL (EX: SCHEDULE ONCE A WEEK TO KEEP A WEEKS WORTH OF REPLAYS IN THE DB)

DBNAME="servatrice"					#set this to the database name used
TABLEPREFIX="cockatrice"			#set this to the prefix used for the table names in the database (do not inclue the _)
SQLCONFFILE="./mysql.cnf" 			#set this to the path that contains the mysql.cnf file
mysql --defaults-file=$SQLCONFFILE -h localhost -e 'truncate table ""$DBNAME"".""$TABLEPREFIX""_replays;truncate table ""$DBNAME"".""$TABLEPREFIX""_replays_access'
