#ifndef COCKATRICE_VISUAL_DECK_EDITOR_DISPLAY_TYPE_H
#define COCKATRICE_VISUAL_DECK_EDITOR_DISPLAY_TYPE_H

enum class DisplayType
{
    Flat,
    Overlap
};

#endif // COCKATRICE_VISUAL_DECK_EDITOR_DISPLAY_TYPE_H
