######################################################################
# Automatically generated by qmake (2.01a) So. Okt 25 12:02:12 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += protocol.h widget.h protocol_commands.h
SOURCES += main.cpp protocol.cpp widget.cpp protocol_commands.cpp

CONFIG += qt debug
