export const Types = {
  CLEAR_STORE: '[Games] Clear Store',
  GAME_JOINED: '[Games] Game Joined',
  GAME_LEFT: '[Games] Game Left',
  GAME_CLOSED: '[Games] Game Closed',
  GAME_HOST_CHANGED: '[Games] Game Host Changed',
  GAME_STATE_CHANGED: '[Games] Game State Changed',
  PLAYER_JOINED: '[Games] Player Joined',
  PLAYER_LEFT: '[Games] Player Left',
  PLAYER_PROPERTIES_CHANGED: '[Games] Player Properties Changed',
  KICKED: '[Games] Kicked',
  CARD_MOVED: '[Games] Card Moved',
  CARD_FLIPPED: '[Games] Card Flipped',
  CARD_DESTROYED: '[Games] Card Destroyed',
  CARD_ATTACHED: '[Games] Card Attached',
  TOKEN_CREATED: '[Games] Token Created',
  CARD_ATTR_CHANGED: '[Games] Card Attribute Changed',
  CARD_COUNTER_CHANGED: '[Games] Card Counter Changed',
  ARROW_CREATED: '[Games] Arrow Created',
  ARROW_DELETED: '[Games] Arrow Deleted',
  COUNTER_CREATED: '[Games] Counter Created',
  COUNTER_SET: '[Games] Counter Set',
  COUNTER_DELETED: '[Games] Counter Deleted',
  CARDS_DRAWN: '[Games] Cards Drawn',
  CARDS_REVEALED: '[Games] Cards Revealed',
  ZONE_SHUFFLED: '[Games] Zone Shuffled',
  DIE_ROLLED: '[Games] Die Rolled',
  ACTIVE_PLAYER_SET: '[Games] Active Player Set',
  ACTIVE_PHASE_SET: '[Games] Active Phase Set',
  TURN_REVERSED: '[Games] Turn Reversed',
  ZONE_DUMPED: '[Games] Zone Dumped',
  ZONE_PROPERTIES_CHANGED: '[Games] Zone Properties Changed',
  GAME_SAY: '[Games] Game Say',
} as const;
