export enum FormKey {
	ADD_TO_BUDDIES = 'ADD_TO_BUDDIES',
	ADD_TO_IGNORE = 'ADD_TO_IGNORE',
	CARD_IMPORT = 'CARD_IMPORT',
	CONNECT = 'CONNECT',
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	SEARCH_LOGS = 'SEARCH_LOGS',
}
