name: Clangify

on:
  pull_request:
    branches:
    - master

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang-format
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends clang-format

    - name: Run clangify
      shell: bash
      run: ./.ci/lint.sh
