name: Code Style (C++) 

on:
  # Push trigger not needed for linting, we do not allow direct pushes to master
  pull_request:
    paths:
      - '*/**'    # matches all files not in root
      - '!**.md'
      - '!.ci/**'
      - '!.github/**'
      - '!.tx/**'
      - '!doc/**'
      - '.ci/lint_cpp.sh'
      - '.github/workflows/desktop-lint.yml'
      - '.clang-format'
      - '.cmake-format.json'
      - 'format.sh'

jobs:
  format:
    runs-on: ubuntu-slim

    steps:
    - name: "Checkout"
      uses: actions/checkout@v7
      with:
        fetch-depth: 20    # should be enough to find merge base

    - name: "Install dependencies"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          clang-format \
          cmake-format \
          shellcheck

    - name: "Check code formatting"
      shell: bash
      run: ./.ci/lint_cpp.sh
