name: Build Docker Container

on:
  push:
    tags:
      - '*Release*'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/docker-release.yml'
      - 'CMakeLists.txt'
      - 'LICENSE'
      - 'README.md'
      - 'Dockerfile'
      - 'servatrice/**'
      - 'common/**'
      - 'cmake/**'
      - '!**.md'

jobs:
  docker:
    name: amd64 & arm64
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/cockatrice/servatrice
          labels: |
            org.opencontainers.image.title=Servatrice
            org.opencontainers.image.url=https://cockatrice.github.io/
            org.opencontainers.image.description=Server for cockatrice, a cross-platform virtual tabletop for multiplayer card games
          annotations: |
            org.opencontainers.image.title=Servatrice
            org.opencontainers.image.url=https://cockatrice.github.io/
            org.opencontainers.image.description=Server for cockatrice, a cross-platform virtual tabletop for multiplayer card games  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
