name: Generate and Deploy Doxygen Docs

on:
  push:
    tags:
      - '*' # Only re-generate docs when a new version is pushed

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Doxygen and Graphviz
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Deploy to cockatrice.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
          external_repository: Cockatrice/cockatrice.github.io
          publish_branch: main
          publish_dir: ./html
          destination_dir: docs   # Docs will live under https://cockatrice.github.io/docs/
